### ISSUE TITLE
Death?

### ISSUE THREAD

**Issue by joshskains** [bflad/chef-jira#15]
Is this project dead?

**Comment by mvdkleijn** [comment]
You can try https://github.com/afklm/chef-jira

**Comment by PierreRambaud** [comment]
ping @bflad

**Comment by mvdkleijn** [comment]
FYI... we've not had any response from @bflad since mid January or so. Initially we forked this repo just to fix some issues we had with the cookbook and contribute the fixes back.

Since there still has been no reply and our fork was kept generic, we decided yesterday to make the fork permanent. It lives at https://github.com/afklm/chef-jira

We'll start cleaning it up and PRs are welcome there.

**Comment by patcon** [comment]
@bflad bumping one more time. Might you be assigning new maintainers, or should we move to building on @mvdkleijn's active fork?

Related: https://github.com/afklm/chef_jira/issues/7

**Comment by bflad** [comment]
I'd suggest switching over to the much better and supported afklm fork, which is now officially the `jira` cookbook: https://supermarket.chef.io/cookbooks/jira - see #22 for discussion and details.
